name: Deploy Production
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    uses: cloudposse/github-actions-workflows/.github/workflows/cd-ecs.yml@deploy-ecs
    with:
      image: ${{ secrets.registry }}/${{ inputs.organization }}/${{ inputs.repository }}
      tag: ${{ inputs.version }}
      repository: ${{ github.event.repository.name }}
      spacelift-organization: ${{ github.event.repository.owner.login }}
      environment: production
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"
      secret-outputs-passphrase: "${{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE }}"
      spacelift-api-key-id: ${{ secrets.SPACELIFT_API_KEY_ID }}
      spacelift-api-key-secret: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
