name: Main Branch
on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  run:
    uses: cloudposse/github-actions-workflows/.github/workflows/dockerized-app-main-branch.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      registry: registry.hub.docker.com
    secrets:
      docker-login: "${{ secrets.DOCKERHUB_USERNAME }}"
      docker-password: "${{ secrets.DOCKERHUB_PASSWORD }}"
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"
