name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  perform:
    uses: cloudposse/github-actions-workflows/.github/workflows/dockerized-app-release.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      registry: "${{ secrets.ECR_REGISTRY }}"
      version: ${{ github.event.release.tag_name }}
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"
